# Project metadata for humans to read
# Not used by the application at runtime

project-meta:
  project-name: CobCash
  author: Ethan Kletschke
  date-started: 2026-01-25
  last-updated: 2026-02-09
  languages: 
    - COBOL (GnuCOBOL)
  status: Work-in-progress
  license: MIT
  version: 1.0.0

build:
  dev-environments:
    - Windows 11
  test-environments: 
    - Windows 11
  target-platforms: 
    - Windows 10
    - Windows 11
  compiler:
    compiler-name: cobc (GnuCOBOL)
    static-compiler: false
    compiler-version: 3.2

team:
  author: Ethan Kletschke
  contributors:
    - Ethan Kletschke
