# Project metadata for humans to read
# Not used by the application at runtime

project-meta:
  project-name: CobCash
  author: Ethan Kletschke
  date-started: 2026-01-25
  last-updated: 2026-02-03
  language: COBOL (GnuCOBOL)
  status: Experimental
  license: MIT
  version: 0.0.4

build:
  developed-on: Windows 11
  tested-on: Windows 11
  target-platform: Windows
  compiler:
    compiler-name: cobc (GnuCOBOL)
    compiler-version: 3.2
