# Project metadata for humans to read
# Not used by the application at runtime

project-meta:
  project-name: CobCash
  language: GnuCOBOL
  status: Experimental
  license: MIT
  version: 0.0.3

build:
  developed-on: Windows 11
  tested-on: Windows 11
  target-platform: Windows
