# Project metadata for humans to read
# Not used by the application at runtime

project-meta:
  project-name: CobCash
  date-started: 2026-01-25
  last-updated: 2026-02-09
  languages:
    - COBOL (GnuCOBOL)
  status: Stable
  license: MIT
  version: 1.0.0

build:
  dev-environments:
    - Windows 11
  test-environments:
    - Windows 11
  target-platforms:
    - Windows 11
  compiler:
    compiler-name: cobc (GnuCOBOL)
    static-compiler: false
    compiler-version: 3.2.0

team:
  author: Ethan Kletschke
  owner: Ethan Kletschke
  contributors:
    - name: Ethan Kletschke
      role: Author and Owner
      github-username: ethanKletschke
      website: https://ethankletschke.netlify.app
