name:  Bug report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Please fill out all required fields.

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of my app are you running?
      placeholder: v1.0.0
    validations:
      required: true 

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs or drag screenshots here if possible
